version: "3.8"

volumes:
  rabbitmq_data:

services:
 
  ###################################
  # Notification: The Notification microservice
  ###################################
  notification:
    build:
      context: ./Notification
      dockerfile: notification.dockerfile
    image: ethantfw/notification:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/Notification
      PYTHONUNBUFFERED: 1
    ports:
      - "5004:5004"

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json
      - rabbitmq_data:/var/lib/rabbitmq

  ###################################
  # User: The User microservice
  ###################################
  user:
    build:
      context: ./Users
      dockerfile: user.dockerfile
    image: ethantfw/user:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/Users
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5000"

  ###################################
  # Auction: The Auction microservice
  ###################################
  auction:
    build:
      context: ./Auction
      dockerfile: auction.dockerfile
    image: ethantfw/auction:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/Auction
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"

  ###################################
  # Bid: The Auction microservice
  ###################################
  bids:
    build:
      context: ./Bids
      dockerfile: bids.dockerfile
    image: ethantfw/bids:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/bids
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"

  ###################################
  # Schedule: The Schedule microservice
  ###################################
  schedule:
    build:
      context: ./Schedule
      dockerfile: schedule.dockerfile
    image: ethantfw/schedule:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/Schedule
      PYTHONUNBUFFERED: 1
    ports:
      - "5003:5003"


  #################################################
  # pricePredictor: The pricePredictor microservice (complex)
  #################################################
  pricePredictor:
    build:
      context: ./PricePredictor
      dockerfile: pricePredictor.dockerfile
    image: ethantfw/pricepredictor:esd
    restart: always
    environment:      
      PYTHONUNBUFFERED: 1
    ports:
      - "5008:5008"




  #################################################
  # createNotification: The createNotification microservice (complex)
  #################################################
  createNotification:
    build:
      context: ./createNotification
      dockerfile: createNotification.dockerfile
    image: ethantfw/createnotification:esd
    restart: always
    depends_on:
      - rabbitmq
      - user
      - auction
      - notification
      - schedule
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      a_queue_name: Notification
      user_url: http://user:5000/user
      auction_url: http://auction:5001/auction 
      notification_url: http://notification:5004/notification 
      schedule_url: http://schedule:5003/schedule  
      PYTHONUNBUFFERED: 1


  #################################################
  # test: The test microservice (complex)
  #################################################
  test:
    build:
      context: ./
      dockerfile: test.dockerfile
    image: ethantfw/test:esd
    restart: always
    depends_on:
      - rabbitmq
      - user
      - auction
      - notification
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      a_queue_name: Notification
      user_url: http://user:5000/user
      auction_url: http://auction:5001/auction 
      notification_url: http://notification:5004/notification 
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"

  

  #################################################
  # createAuction: The createAuction microservice (complex)
  #################################################
  createAuction:
    build:
      context: ./CreateAuction
      dockerfile: createAuction.dockerfile
    image: ethantfw/createauction:esd
    restart: always
    depends_on:
      - auction
      - schedule
    environment:      
      auction_url: http://auction:5001/auction 
      schedule_url: http://schedule:5003/schedule 
      PYTHONUNBUFFERED: 1
    ports:
      - "5010:5010"




  #################################################
  # processBid: The processBid microservice (complex)
  #################################################
  processBid:
    build:
      context: ./ProcessBid
      dockerfile: ProcessBid.dockerfile
    image: ethantfw/processbid:esd
    restart: always
    depends_on:
      - rabbitmq
      - auction
      - bids
    environment:      
      rabbit_host: rabbitmq
      rabbit_port: 5672
      a_queue_name: Notification
      auction_url: http://auction:5001/auction 
      bids_url: http://bids:5002/bid
      PYTHONUNBUFFERED: 1
    ports:
      - "5006:5006"


  #################################################
  # ProcessWinner: The ProcessWinner microservice (complex)
  #################################################
  processWinner:
    build:
      context: ./ProcessWinner
      dockerfile: processWinner.dockerfile
    image: ethantfw/processwinner:esd
    restart: always
    depends_on:
      - rabbitmq
      - auction
      - bids
    environment:      
      rabbit_host: rabbitmq
      rabbit_port: 5672
      a_queue_name: Notification
      auction_url: http://auction:5001/auction 
      bids_url: http://bids:5002/bids 
      PYTHONUNBUFFERED: 1
    ports:
      - "5005:5005"






  # #use this for complex microservice
  # ###############################################
  # # Place Order: The Place Order microservice
  # ###############################################
  # place_order:
  #   build:
  #     context: ./
  #     dockerfile: place_order.dockerfile
  #   image: wangkaijie2001/place_order:esd
  #   restart: always
  #   depends_on:
  #     - order
  #     - shipping_record
  #     - activity_log
  #     - error
  #     - rabbitmq
  #   environment:
  #     rabbit_host: rabbitmq
  #     rabbit_port: 5672
  #     order_URL: http://order:5001/order
  #     shipping_record_URL: http://shipping_record:5002/shipping_record 
  #     PYTHONUNBUFFERED: 1
  #   ports:
  #     - "5100:5100"

  # ##################################
  # # Book: The Book microservice
  # ##################################
  # book:
  #   build:
  #     context: ./
  #     dockerfile: book.dockerfile
  #   image: wangkaijie2001/book:esd
  #   restart: always
  #   environment:
  #     dbURL: mysql+mysqlconnector://@host.docker.internal:3306/book
  #     PYTHONUNBUFFERED: 1
  #   ports:
  #     - "5000:5000"
